name: Bot CI

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: print workign directory
        run: pwd

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest -r discord-bot/requirements.txt

      - name: Lint
        run: |
          pylint --fail-under=7 discord-bot/bot.py
          pytest

  # come back to docker stuff when i have time
  #deploy:
    #runs-on: ubuntu-latest
    #needs: test              # only run if it passes tests

    #steps:
      #- name: Checkout
      #  uses: actions/checkout@v4

      #- name: Set Up Python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.10'

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install -r discord-bot/requirements.txt

      #- name: Build Docker Image
      #  run: |
      #    docker build -t discord-steam-bot ./discord-bot

      #TBD
      #- name: Run Docker Container
      #  run: echo hello world
